services:

  postgres:
    image: postgres:15.6-alpine
    environment:
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Passw0rd
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data

  elasticsearch:
    image: elasticsearch:8.15.0
    expose:
      - 9200
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=Passw0rd*
    networks:
      - es-net
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.15.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    expose:
      - 5601
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - kibana-data:/usr/share/kibana/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssql_volume_data:/var/opt/mssql

  # komut satırından tek bir imaj için :docker compose build identity-svc
  # hepsi için :docker compose build
  identity-svc:
    image: gamestoremicroservice/identity-svc:latest
    build: 
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=Passw0rd;Database=Gamestore_Users_DB
    depends_on:
      - postgres
    ports:
      - 5001:80
  order-svc:
    image: gamestoremicroservice/order-svc:latest
    build: 
      context: .
      dockerfile: src/OrderService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AuthorirtyServiceUrl=http://identity-svc
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=MyMicroservice_OrderDb;User Id=sa;Password=Passw0rd;TrustServerCertificate=true
      - RabbitMq__Host=rabbitmq
      - GrpcGame=http://game-svc:9999
    depends_on:
      - mssql
      - rabbitmq
    ports:
      - 8004:80
  gateway-svc:
    image: gamestoremicroservice/gateway-svc:latest
    build: 
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
  game-svc:
    image: gamestoremicroservice/game-svc:latest
    build: 
      context: .
      dockerfile: src/GameService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:9999
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=Passw0rd;Database=Gamestore_DB
      - AuthorirtyServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:9999
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 8003:80
      - 9999:9999
    depends_on:
      - postgres
      - rabbitmq
  discount-svc:
    image: gamestoremicroservice/discount-svc:latest
    build: 
      context: .
      dockerfile: src/DiscountService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:8888
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=Passw0rd;Database=Microservices_GSteam_Discount
      - AuthorirtyServiceUrl=http://identity-svc
      - GrpcGame=http://game-svc:9999
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:8888
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 8000:80
      - 8888:8888
    depends_on:
      - postgres
  basket-svc:
    image: gamestoremicroservice/basket-svc:latest
    build: 
      context: .
      dockerfile: src/BasketService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RedisDatabase=redis
      - RabbitMq__Host=rabbitmq
      - AuthorirtyServiceUrl=http://identity-svc
      - GrpcDiscount=http://discount-svc:8888
    ports:
      - 8001:80
    depends_on:
      - postgres
      - rabbitmq
      - redis
  search-svc:
    image: gamestoremicroservice/search-svc:latest
    build: 
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:Passw0rd@mongodb
    ports:
      - 8005:80
    depends_on:
      - mongodb
      - rabbitmq
  filter-svc:
    image: gamestoremicroservice/filter-svc:latest
    build: 
      context: .
      dockerfile: src/FilterService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - Elastic__Url=http://elasticsearch:9200
      - indexName=filter_game
    ports:
      - 8002:80
    depends_on:
      - elasticsearch
      - rabbitmq
networks:
  es-net:
    driver: bridge
volumes:
  pgdata:     
  mongodata:
  elasticsearch-data:
  kibana-data:
  redis_volume_data:
  mssql_volume_data:
